
export const ADDTO_CART_REQUEST = 'ADDTO_CART_REQUEST'
export const ADDTO_CART_SUCCESS = 'ADDTO_CART_SUCCESS'
export const ADDTO_CART_FAILURE = 'ADDTO_CART_REQUEST'
export const DUPLICATE = 'DUPLICATE'

export const DELETE_CARTITEM_REQUEST = 'DELETE_CARTITEM_REQUEST'
export const DELETE_CARTITEM_SUCCESS = 'DELETE_CARTITEM_SUCCESS'
export const DELETE_CARTITEM_FAILURE = 'DELETE_CARTITEM_FAILURE'

