
export const ADDTO_WISHLIST_REQUEST = 'ADDTO_WISHLIST_REQUEST'
export const ADDTO_WISHLIST_SUCCESS = 'ADDTO_WISHLIST_SUCCESS'
export const ADDTO_WISHLIST_FAILURE = 'ADDTO_WISHLIST_FAILURE'
export const DUPLICATE = 'DUPLICATE'

export const DELETE_WISHLIST_LOADING = 'DELETE_WISHLIST_LOADING'
export const DELETE_WISHLIST_SUCCESS = 'DELETE_WISHLIST_SUCCESS'
export const DELETE_WISHLIST_FAILURE = 'DELETE_WISHLIST_FAILURE'

